[project]
name = "cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mediapipe",
    "opencv-python",
    "numpy",
    "pillow",
    "ultralytics>=8.3.214",
    "pyzbar>=0.1.9",
    "opencv-contrib-python>=4.11.0.86",
    "qrcode[pil]>=8.2",
]
