"""simplify_detection_model_remove_redundant_fields

Revision ID: 2a72fc901857
Revises: d3e66c1da00e
Create Date: 2025-10-15 22:17:47.033671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a72fc901857'
down_revision = 'd3e66c1da00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new detection_time column as nullable first
    op.add_column('detection', sa.Column('detection_time', sa.DateTime(), nullable=True))
    
    # Migrate existing data: use last_detection_time as detection_time
    op.execute("UPDATE detection SET detection_time = last_detection_time WHERE detection_time IS NULL")
    
    # Make detection_time non-nullable
    op.alter_column('detection', 'detection_time', nullable=False)
    
    # Drop the old columns
    op.drop_column('detection', 'last_detection_time')
    op.drop_column('detection', 'first_detection_time')
    op.drop_column('detection', 'elapsed_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('elapsed_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('detection', sa.Column('first_detection_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('detection', sa.Column('last_detection_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('detection', 'detection_time')
    # ### end Alembic commands ###
