"""Add Detection model for person detection tracking

Revision ID: 3b50e4f754a5
Revises: 58c42442e3e8
Create Date: 2025-10-15 18:57:39.591963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b50e4f754a5'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('bbox_x1', sa.Integer(), nullable=False),
    sa.Column('bbox_y1', sa.Integer(), nullable=False),
    sa.Column('bbox_x2', sa.Integer(), nullable=False),
    sa.Column('bbox_y2', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('elapsed_time', sa.Float(), nullable=False),
    sa.Column('first_detection_time', sa.Float(), nullable=False),
    sa.Column('last_detection_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_person_id'), 'detection', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_person_id'), table_name='detection')
    op.drop_table('detection')
    # ### end Alembic commands ###
