"""update_detection_timestamps_to_datetime

Revision ID: d3e66c1da00e
Revises: b0a6c83b5da8
Create Date: 2025-10-15 22:04:10.572485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3e66c1da00e'
down_revision = 'b0a6c83b5da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert unix timestamps to datetime using PostgreSQL's to_timestamp function
    op.execute("ALTER TABLE detection ALTER COLUMN first_detection_time TYPE TIMESTAMP WITHOUT TIME ZONE USING to_timestamp(first_detection_time)")
    op.execute("ALTER TABLE detection ALTER COLUMN last_detection_time TYPE TIMESTAMP WITHOUT TIME ZONE USING to_timestamp(last_detection_time)")
    op.alter_column('detection', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('detection', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('detection', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # Convert datetime back to unix timestamps using PostgreSQL's extract function
    op.execute("ALTER TABLE detection ALTER COLUMN last_detection_time TYPE DOUBLE PRECISION USING extract(epoch from last_detection_time)")
    op.execute("ALTER TABLE detection ALTER COLUMN first_detection_time TYPE DOUBLE PRECISION USING extract(epoch from first_detection_time)")
    # ### end Alembic commands ###
